apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test_service
    service: test_service
spec:
  selector:
    app: test_service
    service: test_service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP