apiVersion: v1
kind: Service
metadata:
  name: test-service-db
  labels:
    app: test_service-db
    service: test_service
spec:
  selector:
    app: test_service-db
    service: test_service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP